AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'Gemfile'

Rails:
  Enabled: true
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Max: 100
