language: ruby
rvm:
  - 2.3.1
bundler_args: --without production
env:
  - DATABASE_USERNAME: travis
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - CODECLIMATE_REPO_TOKEN=<%= ENV['CODECLIMATE_REPO_TOKEN'] %> bundle exec rspec spec
services:
  - mysql
  - redis-server
before_script:
  - mysql -e 'create database mcg_test;'
branches:
  only:
    - master
