language: ruby
rvm:
- 2.3.1
bundler_args: "--without production"
env:
  matrix:
  - DATABASE_USERNAME: travis
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- CODECLIMATE_REPO_TOKEN=<%= ENV['code_climate'] %> bundle exec rspec spec
services:
- mysql
- redis-server
before_script:
- mysql -e 'create database mcg_test;'
branches:
  only:
  - master
addons:
  code_climate:
    repo_token:
      secure: yoKPWrGKnw2Zce7cclCghJuA2H6WFW8Eq3DJQZNLBa9ICxmhxX3ejCRDadAacnmsH17r27I3ZsoWMdSeFUCa/+zyt4MQMOauIcMVz49GbLCZRsF2CQXeE0Lp/D12/9jlYJhk0Weis6ebW+pt5GezEqiR+ovPI6ErYBgCWmcuZ3hyvEVz2bqMl2E+d/o4cS0u41v/iik5s4ewWJvPb9KUSzk6CRpa8ISloc0gdP2o5gStEl9KbLN/ZpyIux+h+gAEgMyi6c4mZFTZOHEU5PJejePzzVJajMNc2uv6l8MrOIRXj72uYRGB1v3/JwsdQNwrj3A+SaoK+rq9LshkK3PwQRUnNC0kpVQNjbMp6GFafA3RHbv9MDUFFx/JnisPi+5ZPPCvIBuMG/yPP3lhXNdOsFHtspIX3uddhzu6ae5OMiwTR/CVoeDm/lheVsE2K2qopThEibNpr/+oKsS3LIVMI9HoETdgAW3FukrunpLqqBx3xQ09ooAIjDSiAs1hfulnp6OO8a8GCZpF5VYJNVEE7eyJG95i1YGgHyv9o6PG2ae4SzLOHdhIpocP72jWgXap2sLEqebfHoylqu3V0cKpGofNz4tB5tgM0mXenmhXlXLXkSrXY8D65xkIaJyD88z6jZeuUaAWSv3MU9gMw7nADTBAXEAXlQpTNTGbbq44r/c=
