language: ruby
rvm:
- 2.3.1
bundler_args: "--without production"
env:
  matrix:
  - DATABASE_USERNAME: travis
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec spec
services:
- mysql
- redis-server
before_script:
- mysql -e 'create database mcg_test;'
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: NmFl6fVcHlT+P97uF4nuMvCOkJY8T/SMF2ZB6Hb5FXfQniMhuMJ2uN8VZ0NUwq897jCyf9Mq9GT8iOdt2lnZPSkyGlxJ7m8laW+UXdHDGG/tuJjFhNk0Hk33aqBaZPqkJzBtfUOiVIqkN359tfUzWvgUtuUvaQox5E9CeYNghbI2yWJKURa8diWDofBA12G4vSnZT2pr6nUjOSXpVpD9npZNjaAvcBp4FMVvJd3kVFfjyjIp24oNPw3i4C/UjXNSNN8/Z2mSqLdVrebRLh6DesuE6Sgf8rRVR4yrPWoogsPwdvQ/yjcvMqkyamY6otrVgYh1ogLuunFRB+Pjz3Sw9VjqOfoLAF8iEceqnf53/jjvIMk5q6SB1HPJUTKgp4ZctIt3bjGngEjmbhpnk9Ru7QLp1vbFequ+GUoArk++aIdvbG9zG2vMK7t4BVC4tS6RZ770Ubi2+toX/cBQJjy1/07e77CGHD3gWy4PXC25+YdFQ+ZcxeXB5jyuluHTeSXGTkMHNVltATA2k+Zd668vaJgkxvaUBZ0y3s6XutH8YkUiThzzvBnFM6bWcxdZLxgZfmoR3AQ0K8GwskjwEwnufD3A4msH9eFap/1L5XQKY9i8cMg3RRIt8anke52Plyy4uE4Mw14gWvS6BUfyBPD+fLyD6R5bgD002w7jjBNSUHA=
addons:
  code_climate:
    repo_token:
      secure: qBii64ruXNu7LNFXyD/nslBL0aB8eAlFz2hfXBkIQTLOT/UnCqXasAXBjAZqB4XkPtJK4nCiPXsEose9RCA4wclAu5Y3k9vCJRhokta12wYQk/6X/bFrxuvd7Yr1cCb7vnOdOKdhJ20iprijYxavtTqn3FcO4pS/aDWk7ln2ux4lRERPA1bE7uQ053a3geLxk/OBDGWxveVQmA1JAC7v9fwByoipg/WRuYUEqaeH3iTLdvkc7kjiP20SYMwIIyXfKYqBbk19vbrizst+GPVxP3Y3+6vT3RKZRxo8xTf6JNRTzPdr1MYjYLIeRffM7DADE3n1fH5cL97SJy9fhFRNBxbuC3TSk+dmKBLP/pqnjf5fSEsNcj0HZt6mytpwx/+r1dK9ES9S+lNeUBGu4ATvalQcMBqr/wFdrNaVt3b7T225xr900Cc0LTIpcwDPVP+vdzB+f+gIlQe/pBhqYb5rum+IG/F+pAf48mwGwGpKXeqaDdLTA9MY4bNTgKkWj8GnM7rJ6iBcp2xYbgBVDptL90oV5fQDbCjVjKaU3cEY8onO0/MgOEI5R7767TDV97F7zoSzX1J+JmHOClUq9IeDMeryA7rT+Pj5QUVd93ZHhKiq5wQ/xySSho+OHyhNA7yQkhZN7zKywIWWzesVSC+d6oF3+v1BSBKR2G5mCQViC+I=
