sqlite: &sqlite
  adapter: sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

default: &default
 <<: *mysql

development:
  <<: *default
  # database: mcg_development
  database: db/development.sqlite3
test:
  <<: *default
  # database: mcg_test
  database: db/test.sqlite3
production:
  <<: *mysql
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: mcg_production
